version: '1'
services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            # - certs:/etc/nginx/certs
            # - vhostd:/etc/nginx/vhost.d
            # - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock

    client:
        image: 'maximillllian/black-lotos-cv:latest'
        container_name: 'black-lotos'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - VIRTUAL_PORT=8080
            - VIRTUAL_HOST=blacklotos.ru, www.blacklotos.ru, localhost
        volumes:
            # - certs:/etc/nginx/certs
            # - vhostd:/etc/nginx/vhost.d
            # - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/app
            - /app/node_modules
