version: '1'
services:
    client:
        image: 'client-dev'
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:8081'
        volumes:
            - .:/app
            - /app/node_modules
