version: '3'
services:
    client:
        image: 'client-dev'
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '8080:8000'
        volumes:
            - .:/app
            - /app/node_modules
