name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      host_address: blacklotos.ru,www.blacklotos.ru,localhost
      image_name: maximillllian/black-lotos:${{ github.sha }}
    secrets: inherit