name: Manually deploy
on:
  workflow_dispatch:

jobs:
  deploy_manually:
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      host_address: ${{ github.ref_name }}.blacklotos.ru
      image_name: maximillllian/black-lotos-${{ github.ref_name }}:${{ github.sha }}
      container_name: black-lotos-${{ github.ref_name }}
      kill_after: 50
    secrets: inherit   