name: Manually deploy
on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

jobs:
    get_branch_name:
      runs-on: ubuntu-latest
      outputs:
        ref_name: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }} 
      steps:
        - name: get pull request ref
          id: get_pull_request_ref
          uses: octokit/request-action@v2.x
          with:
            route: GET /repos/:repository/pulls/:issue_id
            repository: ${{ github.repository }}
            issue_id: ${{ github.event.issue.number }}
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    check_need_deploy:
        runs-on: ubuntu-latest
        outputs:
            triggered: ${{ steps.check.outputs.triggered }}
        steps:
            - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
              id: check
              with:
                  trigger: '/deploy'
                  reaction: rocket
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    deploy_manually:
        needs: [check_need_deploy, get_branch_name]
        if: needs.check_need_deploy.outputs.triggered == 'true'

        uses: ./.github/workflows/reusable_deploy.yml
        with:
            host_address: ${{ needs.get_branch_name.outputs.ref_name }}.blacklotos.ru
            image_name: maximillllian/black-lotos-${{ needs.get_branch_name.outputs.ref_name }}:${{ github.sha }}
            # При изменении еще поправить ниже в CONTAINER_NAME
            container_name: black-lotos-${{ needs.get_branch_name.outputs.ref_name }}
        secrets: inherit
    comment:
        needs: [deploy_manually, get_branch_name]
        if: needs.check_need_deploy.outputs.triggered == 'true'

        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              env:
                  HOST_ADDRESS: ${{ needs.get_branch_name.outputs.ref_name }}.blacklotos.ru
              with:
                  script: |
                      const { HOST_ADDRESS } = process.env 
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Review app successfully deployed [${HOST_ADDRESS}](http://${HOST_ADDRESS})`
                      })
    kill:
        needs: [deploy_manually, get_branch_name]
        if: needs.check_need_deploy.outputs.triggered == 'true'
        runs-on: ubuntu-latest

        steps:
            - name: kill_app
              env:
                  KILL_AFTER: '50s'
                  PSWD: ${{ secrets.PSWD }}
                  USER: ${{ secrets.USER }}
                  HOST: ${{ secrets.HOST }}
                  CONTAINER_NAME: black-lotos-${{ needs.get_branch_name.outputs.ref_name }}
              run: |
                  sshpass -p ${{ env.PSWD }} ssh -v -o StrictHostKeyChecking=no ${{ env.USER }}@${{ env.HOST }} <<'ENDSSH'
                  sleep ${{ env.KILL_AFTER }}
                  docker stop ${{ env.CONTAINER_NAME }}
                  docker rm ${{ env.CONTAINER_NAME }}
                  ENDSSH
