name: Manually deploy
on:
  workflow_dispatch:
    
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      host_address: ${{ github.ref_name }}.blacklotos.ru
    secrets: inherit