name: Manually deploy
on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

jobs:
    check_need_deploy:
        runs-on: ubuntu-latest
        outputs:
            triggered: ${{ steps.check.outputs.triggered }}
        steps:
            - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0

              id: check
              with:
                  trigger: '/deploy'
                  reaction: rocket
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    deploy_manually:
        needs: check_need_deploy
        if: needs.check_need_deploy.outputs.triggered == 'true'

        uses: ./.github/workflows/reusable_deploy.yml
        with:
            host_address: ${{ github.ref_name }}.blacklotos.ru
            image_name: maximillllian/black-lotos-${{ github.ref_name }}:${{ github.sha }}
            container_name: black-lotos-${{ github.ref_name }}
            kill_after: 50
        secrets: inherit
    comment:
        needs: deploy_manually
        if: needs.check_need_deploy.outputs.triggered == 'true'

        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              env:
                  HOST_ADDRESS: ${{ github.ref_name }}.blacklotos.ru
              with:
                  script: |
                      const { HOST_ADDRESS } = process.env 
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Thanks for reporting! ' + HOST_ADDRESS
                      })
