name: Reusable deploy

on:
  workflow_call:
    inputs:
      host_address: 
        required: true
        type: string
      image_name:
        required: true
        type: string
      container_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY_NAME: ${{ secrets.API_KEY_NAME }}
      API_KEY: ${{ secrets.API_KEY }}
      APP_PATH: ${{ secrets.APP_PATH }}
      CONTAINER_NAME: ${{ inputs.container_name }}
      PSWD: ${{ secrets.PSWD }}
      USER: ${{ secrets.USER }}
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      NGINX_PORT: ${{ secrets.NGINX_PORT }}
      ARTIFACT_HOST: ${{ secrets.ARTIFACT_HOST }}
      ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
      DOCKER_IMAGE: ${{ inputs.image_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Set up SSH
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ env.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ env.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass
      - name: Deploy to server
        run: |
          sshpass -p ${{ env.PSWD }} ssh -v -o StrictHostKeyChecking=no ${{ env.USER }}@${{ env.HOST }} <<'ENDSSH'
          docker pull ${{ env.DOCKER_IMAGE }}
          docker stop ${{ env.CONTAINER_NAME }}
          docker rm ${{ env.CONTAINER_NAME }}
          export ${{ env.API_KEY_NAME }}=${{ env.API_KEY }}
          echo "host_address: ${{ inputs.host_address }}"
          docker run --name ${{ env.CONTAINER_NAME }} \
            -e VIRTUAL_HOST=${{ inputs.host_address }} \
            -e VIRTUAL_PORT=8080 \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            -dit ${{ env.DOCKER_IMAGE }}
          ENDSSH